manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      import:
        # Through name allow list import only Zephyr modules we need:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_st
          - hal_stm32
          - hal_nxp
          - hal_rpi_pico
          - picolibc
    # Kionix driver work repository, name of remote repository followed by name
    # of local dir into which to clone:
    - name: kionix-drivers
      path: kionix-drivers
      revision: main
      url: https://github.com/tedhavelka/kionix-drivers

  self:
    # This repository should be cloned to 
    path: out-of-tree-driver-demo
