manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      import:
        # Through name allow list import only Zephyr modules we need:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_stm32
          - hal_nxp
  self:
    # This repository should be cloned to 
    path: test-project-0127
