#ifndef _KD_DEVELOPMENT_FLAGS
#define _KD_DEVELOPMENT_FLAGS

// KX132-1211 Configuration:
#define DEV_TEST__ENABLE_KX132_1211_ASYNCHRONOUS_READINGS (1)
#define DEV_TEST__SET_KX132_1211_OUTPUT_DATA_RATE         (0)

// KX132-1211 Readings:
#define DEV_TEST__FETCH_AND_GET_MANUFACTURER_ID           (1)
#define DEV_TEST__FETCH_AND_GET_PART_ID                   (1)
#define DEV_TEST__FETCH_ACCELEROMETER_READINGS_XYZ        (1)

// 2021-11-19 -
#define KD_DEV__CONFIG_REGISTERS_SUMMARY_ENABLED          (1)
#define KD_DEV__I2C_WRITE_STATUS                          (1)

#define DEFINE_FOR_USE__ACCELERATOR_START_ACQUISITION_NO_FIFO (0)
#define DEFINE_FOR_USE__READ_OF_IIS2DH_ACC_STATUS_REGISTER    (1)

#endif // _KD_DEVELOPMENT_FLAGS
